esphome:
  name: temp-sensor-1

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temp-Sensor-1 Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# DHT22 sensor configuration entry
sensor:
  - platform: dht
    id: temperature_sensor
    model: AM2302
    pin: D2
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
